### ISSUE TITLE
Add option to delay a drop

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/bubbler#5]
There should be a field on the website to allow people to delay a drop, so that they have time to get to the machine after dropping it so that nobody steals their drink :)

**Comment by Mstrodl** [comment]
> There should be a field on the website to allow people to delay a drop, so that they have time to get to the machine after dropping it so that nobody steals their drink :)

This functionality probably belongs at [ComputerScienceHouse/tonic](https://github.com/ComputerScienceHouse/tonic) or `sleep 30; clink drop bigdrink 1`.
